"use client";

import { useState, useMemo } from "react";
import { motion } from "framer-motion";
import { Check, Copy, FileCode, Palette, Download, Braces, FileJson } from "lucide-react";
import { cn, copyToClipboard, hexToHsl } from "@/lib/utils";
import type { DesignSystem, OutputFormat } from "@/types/design-system";

interface CodeOutputProps {
  designSystem: DesignSystem;
}

const formatOptions: { id: OutputFormat; label: string; icon: React.ReactNode }[] = [
  { id: "css", label: "CSS", icon: <FileCode className="w-4 h-4" /> },
  { id: "tailwind", label: "Tailwind", icon: <Palette className="w-4 h-4" /> },
  { id: "shadcn", label: "shadcn/ui", icon: <Palette className="w-4 h-4" /> },
  { id: "json", label: "JSON Tokens", icon: <Braces className="w-4 h-4" /> },
  { id: "figma", label: "Figma", icon: <FileJson className="w-4 h-4" /> },
];

function generateCSSVariables(ds: DesignSystem): string {
  const { colors, typography, styles } = ds;
  
  return `/* Design System: ${ds.name}
 * Generated by Design Chameleon
 * ${ds.description}
 */

:root {
  /* Color Palette */
  --color-primary: ${colors.primary};
  --color-secondary: ${colors.secondary};
  --color-accent: ${colors.accent};
  
  /* Background & Surface */
  --color-background: ${colors.background};
  --color-foreground: ${colors.foreground};
  --color-card: ${colors.card};
  --color-card-foreground: ${colors.cardForeground};
  --color-muted: ${colors.muted};
  --color-muted-foreground: ${colors.mutedForeground};
  --color-border: ${colors.border};
  
  /* Semantic Colors */
  --color-success: ${colors.success};
  --color-error: ${colors.error};
  --color-warning: ${colors.warning};
  --color-info: ${colors.info};
  
  /* Typography */
  --font-heading: '${typography.headingFont}', system-ui, sans-serif;
  --font-body: '${typography.bodyFont}', system-ui, sans-serif;
  --font-mono: '${typography.monoFont}', monospace;
  
  --font-size-h1: ${typography.headingSizes.h1};
  --font-size-h2: ${typography.headingSizes.h2};
  --font-size-h3: ${typography.headingSizes.h3};
  --font-size-h4: ${typography.headingSizes.h4};
  --font-size-large: ${typography.bodySizes.large};
  --font-size-base: ${typography.bodySizes.base};
  --font-size-small: ${typography.bodySizes.small};
  
  --line-height-heading: ${typography.lineHeight.heading};
  --line-height-body: ${typography.lineHeight.body};
  
  /* Border Radius */
  --radius-none: ${styles.borderRadius.none};
  --radius-sm: ${styles.borderRadius.sm};
  --radius-md: ${styles.borderRadius.md};
  --radius-lg: ${styles.borderRadius.lg};
  --radius-xl: ${styles.borderRadius.xl};
  --radius-full: ${styles.borderRadius.full};
  
  /* Shadows */
  --shadow-sm: ${styles.shadows.sm};
  --shadow-md: ${styles.shadows.md};
  --shadow-lg: ${styles.shadows.lg};
  --shadow-xl: ${styles.shadows.xl};
  
  /* Spacing */
  --spacing-xs: ${styles.spacing.xs};
  --spacing-sm: ${styles.spacing.sm};
  --spacing-md: ${styles.spacing.md};
  --spacing-lg: ${styles.spacing.lg};
  --spacing-xl: ${styles.spacing.xl};
  --spacing-2xl: ${styles.spacing["2xl"]};
}`;
}

function generateTailwindConfig(ds: DesignSystem): string {
  const { colors, typography, styles } = ds;
  
  return `// tailwind.config.ts
// Design System: ${ds.name}
// Generated by Design Chameleon

import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "${colors.primary}",
        secondary: "${colors.secondary}",
        accent: "${colors.accent}",
        background: "${colors.background}",
        foreground: "${colors.foreground}",
        card: {
          DEFAULT: "${colors.card}",
          foreground: "${colors.cardForeground}",
        },
        muted: {
          DEFAULT: "${colors.muted}",
          foreground: "${colors.mutedForeground}",
        },
        border: "${colors.border}",
        success: "${colors.success}",
        error: "${colors.error}",
        warning: "${colors.warning}",
        info: "${colors.info}",
      },
      fontFamily: {
        heading: ["${typography.headingFont}", "system-ui", "sans-serif"],
        body: ["${typography.bodyFont}", "system-ui", "sans-serif"],
        mono: ["${typography.monoFont}", "monospace"],
      },
      fontSize: {
        h1: "${typography.headingSizes.h1}",
        h2: "${typography.headingSizes.h2}",
        h3: "${typography.headingSizes.h3}",
        h4: "${typography.headingSizes.h4}",
        "body-lg": "${typography.bodySizes.large}",
        "body-base": "${typography.bodySizes.base}",
        "body-sm": "${typography.bodySizes.small}",
      },
      lineHeight: {
        heading: "${typography.lineHeight.heading}",
        body: "${typography.lineHeight.body}",
      },
      borderRadius: {
        none: "${styles.borderRadius.none}",
        sm: "${styles.borderRadius.sm}",
        md: "${styles.borderRadius.md}",
        lg: "${styles.borderRadius.lg}",
        xl: "${styles.borderRadius.xl}",
        full: "${styles.borderRadius.full}",
      },
      boxShadow: {
        sm: "${styles.shadows.sm}",
        md: "${styles.shadows.md}",
        lg: "${styles.shadows.lg}",
        xl: "${styles.shadows.xl}",
      },
      spacing: {
        xs: "${styles.spacing.xs}",
        sm: "${styles.spacing.sm}",
        md: "${styles.spacing.md}",
        lg: "${styles.spacing.lg}",
        xl: "${styles.spacing.xl}",
        "2xl": "${styles.spacing["2xl"]}",
      },
    },
  },
  plugins: [],
};

export default config;`;
}

function generateShadcnTheme(ds: DesignSystem): string {
  const { colors, styles } = ds;
  
  const toHSL = (hex: string) => {
    const hsl = hexToHsl(hex);
    return `${hsl.h} ${hsl.s}% ${hsl.l}%`;
  };
  
  return `/* shadcn/ui Theme
 * Design System: ${ds.name}
 * Generated by Design Chameleon
 * 
 * Add this to your globals.css
 */

@layer base {
  :root {
    --background: ${toHSL(colors.background)};
    --foreground: ${toHSL(colors.foreground)};
    
    --card: ${toHSL(colors.card)};
    --card-foreground: ${toHSL(colors.cardForeground)};
    
    --popover: ${toHSL(colors.card)};
    --popover-foreground: ${toHSL(colors.cardForeground)};
    
    --primary: ${toHSL(colors.primary)};
    --primary-foreground: 0 0% 100%;
    
    --secondary: ${toHSL(colors.secondary)};
    --secondary-foreground: 0 0% 100%;
    
    --muted: ${toHSL(colors.muted)};
    --muted-foreground: ${toHSL(colors.mutedForeground)};
    
    --accent: ${toHSL(colors.accent)};
    --accent-foreground: ${toHSL(colors.background)};
    
    --destructive: ${toHSL(colors.error)};
    --destructive-foreground: 0 0% 100%;
    
    --border: ${toHSL(colors.border)};
    --input: ${toHSL(colors.border)};
    --ring: ${toHSL(colors.primary)};
    
    --radius: ${styles.borderRadius.md};
    
    /* Extended semantic colors */
    --success: ${toHSL(colors.success)};
    --warning: ${toHSL(colors.warning)};
    --info: ${toHSL(colors.info)};
  }
}

/* Usage with Tailwind:
 * 
 * bg-primary      → Uses --primary
 * text-foreground → Uses --foreground
 * border-border   → Uses --border
 * 
 * Example component:
 * <div className="bg-card text-card-foreground rounded-lg border shadow-sm">
 *   <h2 className="text-primary">Title</h2>
 *   <p className="text-muted-foreground">Description</p>
 * </div>
 */`;
}

function generateJSONTokens(ds: DesignSystem): string {
  const tokens = {
    $schema: "https://design-tokens.github.io/community-group/format/",
    name: ds.name,
    description: ds.description,
    color: {
      primary: { $value: ds.colors.primary, $type: "color" },
      secondary: { $value: ds.colors.secondary, $type: "color" },
      accent: { $value: ds.colors.accent, $type: "color" },
      background: { $value: ds.colors.background, $type: "color" },
      foreground: { $value: ds.colors.foreground, $type: "color" },
      card: { $value: ds.colors.card, $type: "color" },
      muted: { $value: ds.colors.muted, $type: "color" },
      border: { $value: ds.colors.border, $type: "color" },
      semantic: {
        success: { $value: ds.colors.success, $type: "color" },
        error: { $value: ds.colors.error, $type: "color" },
        warning: { $value: ds.colors.warning, $type: "color" },
        info: { $value: ds.colors.info, $type: "color" },
      },
    },
    typography: {
      fontFamily: {
        heading: { $value: ds.typography.headingFont, $type: "fontFamily" },
        body: { $value: ds.typography.bodyFont, $type: "fontFamily" },
        mono: { $value: ds.typography.monoFont, $type: "fontFamily" },
      },
      fontSize: {
        h1: { $value: ds.typography.headingSizes.h1, $type: "dimension" },
        h2: { $value: ds.typography.headingSizes.h2, $type: "dimension" },
        h3: { $value: ds.typography.headingSizes.h3, $type: "dimension" },
        h4: { $value: ds.typography.headingSizes.h4, $type: "dimension" },
        bodyLarge: { $value: ds.typography.bodySizes.large, $type: "dimension" },
        bodyBase: { $value: ds.typography.bodySizes.base, $type: "dimension" },
        bodySmall: { $value: ds.typography.bodySizes.small, $type: "dimension" },
      },
      fontWeight: {
        heading: { $value: ds.typography.headingWeight, $type: "fontWeight" },
        body: { $value: ds.typography.bodyWeight, $type: "fontWeight" },
      },
      lineHeight: {
        heading: { $value: ds.typography.lineHeight.heading, $type: "number" },
        body: { $value: ds.typography.lineHeight.body, $type: "number" },
      },
    },
    spacing: Object.fromEntries(
      Object.entries(ds.styles.spacing).map(([key, value]) => [
        key,
        { $value: value, $type: "dimension" },
      ])
    ),
    borderRadius: Object.fromEntries(
      Object.entries(ds.styles.borderRadius).map(([key, value]) => [
        key,
        { $value: value, $type: "dimension" },
      ])
    ),
    shadow: Object.fromEntries(
      Object.entries(ds.styles.shadows).map(([key, value]) => [
        key,
        { $value: value, $type: "shadow" },
      ])
    ),
    gradients: ds.gradients.map((g, i) => ({
      name: `gradient-${i + 1}`,
      from: g.from,
      to: g.to,
      via: g.via || null,
      direction: g.direction,
    })),
    metadata: {
      mood: ds.mood,
      suggestedUse: ds.suggestedUse,
      generatedBy: "Design Chameleon",
      generatedAt: new Date().toISOString(),
    },
  };

  return JSON.stringify(tokens, null, 2);
}

function generateFigmaTokens(ds: DesignSystem): string {
  // Figma Tokens plugin format
  const tokens = {
    global: {
      colors: {
        primary: { value: ds.colors.primary, type: "color" },
        secondary: { value: ds.colors.secondary, type: "color" },
        accent: { value: ds.colors.accent, type: "color" },
        background: { value: ds.colors.background, type: "color" },
        foreground: { value: ds.colors.foreground, type: "color" },
        card: { value: ds.colors.card, type: "color" },
        "card-foreground": { value: ds.colors.cardForeground, type: "color" },
        muted: { value: ds.colors.muted, type: "color" },
        "muted-foreground": { value: ds.colors.mutedForeground, type: "color" },
        border: { value: ds.colors.border, type: "color" },
        success: { value: ds.colors.success, type: "color" },
        error: { value: ds.colors.error, type: "color" },
        warning: { value: ds.colors.warning, type: "color" },
        info: { value: ds.colors.info, type: "color" },
      },
      fontFamilies: {
        heading: { value: ds.typography.headingFont, type: "fontFamilies" },
        body: { value: ds.typography.bodyFont, type: "fontFamilies" },
        mono: { value: ds.typography.monoFont, type: "fontFamilies" },
      },
      fontSizes: {
        h1: { value: ds.typography.headingSizes.h1, type: "fontSizes" },
        h2: { value: ds.typography.headingSizes.h2, type: "fontSizes" },
        h3: { value: ds.typography.headingSizes.h3, type: "fontSizes" },
        h4: { value: ds.typography.headingSizes.h4, type: "fontSizes" },
        "body-large": { value: ds.typography.bodySizes.large, type: "fontSizes" },
        "body-base": { value: ds.typography.bodySizes.base, type: "fontSizes" },
        "body-small": { value: ds.typography.bodySizes.small, type: "fontSizes" },
      },
      fontWeights: {
        heading: { value: ds.typography.headingWeight, type: "fontWeights" },
        body: { value: ds.typography.bodyWeight, type: "fontWeights" },
      },
      lineHeights: {
        heading: { value: ds.typography.lineHeight.heading, type: "lineHeights" },
        body: { value: ds.typography.lineHeight.body, type: "lineHeights" },
      },
      spacing: Object.fromEntries(
        Object.entries(ds.styles.spacing).map(([key, value]) => [
          key,
          { value, type: "spacing" },
        ])
      ),
      borderRadius: Object.fromEntries(
        Object.entries(ds.styles.borderRadius).map(([key, value]) => [
          key,
          { value, type: "borderRadius" },
        ])
      ),
      boxShadow: Object.fromEntries(
        Object.entries(ds.styles.shadows).map(([key, value]) => [
          key,
          { value, type: "boxShadow" },
        ])
      ),
    },
    $themes: [],
    $metadata: {
      tokenSetOrder: ["global"],
    },
  };

  return `// Figma Tokens Plugin Format
// Design System: ${ds.name}
// Generated by Design Chameleon
//
// Import this JSON into the Figma Tokens plugin:
// 1. Open Figma Tokens plugin
// 2. Go to Settings > Import
// 3. Paste this JSON

${JSON.stringify(tokens, null, 2)}`;
}

export function CodeOutput({ designSystem }: CodeOutputProps) {
  const [format, setFormat] = useState<OutputFormat>("css");
  const [copied, setCopied] = useState(false);

  const code = useMemo(() => {
    switch (format) {
      case "css":
        return generateCSSVariables(designSystem);
      case "tailwind":
        return generateTailwindConfig(designSystem);
      case "shadcn":
        return generateShadcnTheme(designSystem);
      case "json":
        return generateJSONTokens(designSystem);
      case "figma":
        return generateFigmaTokens(designSystem);
      default:
        return "";
    }
  }, [format, designSystem]);

  const handleDownload = () => {
    const extensions: Record<OutputFormat, string> = {
      css: "css",
      tailwind: "ts",
      shadcn: "css",
      json: "json",
      figma: "json",
    };
    const blob = new Blob([code], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `design-system.${extensions[format]}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    await copyToClipboard(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-4">
      {/* Format Selector */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2 p-1 bg-muted rounded-lg">
          {formatOptions.map((f) => (
            <button
              key={f.id}
              onClick={() => setFormat(f.id)}
              className={cn(
                "flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all",
                format === f.id
                  ? "bg-background text-foreground shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              )}
            >
              {f.icon}
              {f.label}
            </button>
          ))}
        </div>

        <div className="flex items-center gap-2">
          <motion.button
            onClick={handleDownload}
            whileTap={{ scale: 0.95 }}
            className="flex items-center gap-2 px-4 py-2 rounded-lg font-medium bg-muted hover:bg-muted/80 transition-all"
          >
            <Download className="w-4 h-4" />
            Download
          </motion.button>
          <motion.button
            onClick={handleCopy}
            whileTap={{ scale: 0.95 }}
            className={cn(
              "flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-all",
              copied
                ? "bg-success text-white"
                : "bg-primary text-primary-foreground hover:bg-primary/90"
            )}
          >
            {copied ? (
              <>
                <Check className="w-4 h-4" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy
              </>
            )}
          </motion.button>
        </div>
      </div>

      {/* Code Display */}
      <motion.div
        key={format}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.2 }}
        className="relative rounded-xl overflow-hidden border border-border bg-[#0d1117]"
      >
        <div className="flex items-center justify-between px-4 py-3 border-b border-border/50 bg-[#161b22]">
          <span className="text-sm text-muted-foreground font-mono">
            {format === "css" && "styles.css"}
            {format === "tailwind" && "tailwind.config.ts"}
            {format === "shadcn" && "globals.css"}
            {format === "json" && "design-tokens.json"}
            {format === "figma" && "figma-tokens.json"}
          </span>
        </div>
        <pre className="p-4 overflow-auto max-h-[500px] text-sm">
          <code className="text-gray-300 font-mono whitespace-pre">{code}</code>
        </pre>
      </motion.div>
    </div>
  );
}

